// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hmiMsg.proto

#include "hmiMsg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_hmiMsg_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_HeaderMsg_hmiMsg_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_hmiMsg_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_OfflineMsg_hmiMsg_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_hmiMsg_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_OnlineMsg_hmiMsg_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_hmiMsg_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SMBMsg_hmiMsg_2eproto;
class HeaderMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<HeaderMsg> _instance;
} _HeaderMsg_default_instance_;
class SMBMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SMBMsg> _instance;
} _SMBMsg_default_instance_;
class HmiMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<HmiMsg> _instance;
} _HmiMsg_default_instance_;
class OnlineMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<OnlineMsg> _instance;
} _OnlineMsg_default_instance_;
class OfflineMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<OfflineMsg> _instance;
} _OfflineMsg_default_instance_;
class HmiConfigMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<HmiConfigMsg> _instance;
} _HmiConfigMsg_default_instance_;
static void InitDefaultsscc_info_HeaderMsg_hmiMsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_HeaderMsg_default_instance_;
    new (ptr) ::HeaderMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::HeaderMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_HeaderMsg_hmiMsg_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_HeaderMsg_hmiMsg_2eproto}, {}};

static void InitDefaultsscc_info_HmiConfigMsg_hmiMsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_HmiConfigMsg_default_instance_;
    new (ptr) ::HmiConfigMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::HmiConfigMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_HmiConfigMsg_hmiMsg_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_HmiConfigMsg_hmiMsg_2eproto}, {
      &scc_info_HeaderMsg_hmiMsg_2eproto.base,
      &scc_info_OnlineMsg_hmiMsg_2eproto.base,
      &scc_info_OfflineMsg_hmiMsg_2eproto.base,}};

static void InitDefaultsscc_info_HmiMsg_hmiMsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_HmiMsg_default_instance_;
    new (ptr) ::HmiMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::HmiMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_HmiMsg_hmiMsg_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_HmiMsg_hmiMsg_2eproto}, {
      &scc_info_HeaderMsg_hmiMsg_2eproto.base,
      &scc_info_SMBMsg_hmiMsg_2eproto.base,}};

static void InitDefaultsscc_info_OfflineMsg_hmiMsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_OfflineMsg_default_instance_;
    new (ptr) ::OfflineMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::OfflineMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_OfflineMsg_hmiMsg_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_OfflineMsg_hmiMsg_2eproto}, {}};

static void InitDefaultsscc_info_OnlineMsg_hmiMsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_OnlineMsg_default_instance_;
    new (ptr) ::OnlineMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::OnlineMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_OnlineMsg_hmiMsg_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_OnlineMsg_hmiMsg_2eproto}, {}};

static void InitDefaultsscc_info_SMBMsg_hmiMsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_SMBMsg_default_instance_;
    new (ptr) ::SMBMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::SMBMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SMBMsg_hmiMsg_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SMBMsg_hmiMsg_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_hmiMsg_2eproto[6];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_hmiMsg_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_hmiMsg_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_hmiMsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HeaderMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::HeaderMsg, timestamp_),
  PROTOBUF_FIELD_OFFSET(::HeaderMsg, version_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SMBMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::SMBMsg, smb_id_),
  PROTOBUF_FIELD_OFFSET(::SMBMsg, vol_10mv_),
  PROTOBUF_FIELD_OFFSET(::SMBMsg, cur_10ma_),
  PROTOBUF_FIELD_OFFSET(::SMBMsg, soc_),
  PROTOBUF_FIELD_OFFSET(::SMBMsg, tmp_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HmiMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::HmiMsg, header_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, en_ctrl_start_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, out_mode_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, dw_vol_mv_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, dw_freq_mhz_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, dw_cur_ma_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, smb_vol_mv_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, smb_cur_ma_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, smb_freq_mhz_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, smb_total_soc_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, smb_dw_phase_diff_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, pf_val_milli_),
  PROTOBUF_FIELD_OFFSET(::HmiMsg, smb_infos_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::OnlineMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::OnlineMsg, start_time_),
  PROTOBUF_FIELD_OFFSET(::OnlineMsg, end_time_),
  PROTOBUF_FIELD_OFFSET(::OnlineMsg, cur_10ma_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::OfflineMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::OfflineMsg, start_time_),
  PROTOBUF_FIELD_OFFSET(::OfflineMsg, end_time_),
  PROTOBUF_FIELD_OFFSET(::OfflineMsg, vol_10ma_),
  PROTOBUF_FIELD_OFFSET(::OfflineMsg, power_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HmiConfigMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::HmiConfigMsg, header_),
  PROTOBUF_FIELD_OFFSET(::HmiConfigMsg, en_set_smb_chacur_10ma_),
  PROTOBUF_FIELD_OFFSET(::HmiConfigMsg, set_smb_discur_10ma_),
  PROTOBUF_FIELD_OFFSET(::HmiConfigMsg, set_smb_chacur_10ma_),
  PROTOBUF_FIELD_OFFSET(::HmiConfigMsg, online1_),
  PROTOBUF_FIELD_OFFSET(::HmiConfigMsg, offline1_),
  PROTOBUF_FIELD_OFFSET(::HmiConfigMsg, online2_),
  PROTOBUF_FIELD_OFFSET(::HmiConfigMsg, offline2_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::HeaderMsg)},
  { 7, -1, sizeof(::SMBMsg)},
  { 17, -1, sizeof(::HmiMsg)},
  { 35, -1, sizeof(::OnlineMsg)},
  { 43, -1, sizeof(::OfflineMsg)},
  { 52, -1, sizeof(::HmiConfigMsg)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_HeaderMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_SMBMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_HmiMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_OnlineMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_OfflineMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_HmiConfigMsg_default_instance_),
};

const char descriptor_table_protodef_hmiMsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014hmiMsg.proto\"/\n\tHeaderMsg\022\021\n\ttimestamp"
  "\030\001 \001(\004\022\017\n\007version\030\002 \001(\t\"V\n\006SMBMsg\022\016\n\006smb"
  "_id\030\001 \001(\r\022\020\n\010vol_10mV\030\002 \001(\r\022\020\n\010cur_10mA\030"
  "\003 \001(\005\022\013\n\003soc\030\004 \001(\r\022\013\n\003tmp\030\005 \001(\005\"\252\002\n\006HmiM"
  "sg\022\032\n\006header\030\001 \001(\0132\n.HeaderMsg\022\025\n\ren_ctr"
  "l_start\030\002 \001(\r\022\020\n\010out_mode\030\003 \001(\r\022\021\n\tdw_vo"
  "l_mV\030\004 \001(\r\022\023\n\013dw_freq_mHz\030\005 \001(\r\022\021\n\tdw_cu"
  "r_mA\030\006 \001(\r\022\022\n\nsmb_vol_mV\030\007 \001(\r\022\022\n\nsmb_cu"
  "r_mA\030\010 \001(\r\022\024\n\014smb_freq_mHz\030\t \001(\r\022\025\n\rsmb_"
  "total_soc\030\n \001(\r\022\031\n\021smb_dw_phase_diff\030\013 \001"
  "(\002\022\024\n\014pf_val_milli\030\014 \001(\002\022\032\n\tsmb_infos\030\r "
  "\003(\0132\007.SMBMsg\"C\n\tOnlineMsg\022\022\n\nstart_time\030"
  "\001 \001(\t\022\020\n\010end_time\030\002 \001(\t\022\020\n\010cur_10mA\030\003 \001("
  "\r\"S\n\nOfflineMsg\022\022\n\nstart_time\030\001 \001(\t\022\020\n\010e"
  "nd_time\030\002 \001(\t\022\020\n\010vol_10mA\030\003 \001(\r\022\r\n\005power"
  "\030\004 \001(\r\"\374\001\n\014HmiConfigMsg\022\032\n\006header\030\001 \001(\0132"
  "\n.HeaderMsg\022\036\n\026en_set_smb_chaCur_10mA\030\002 "
  "\001(\010\022\033\n\023set_smb_disCur_10mA\030\003 \001(\r\022\033\n\023set_"
  "smb_chaCur_10mA\030\004 \001(\r\022\033\n\007online1\030\005 \001(\0132\n"
  ".OnlineMsg\022\035\n\010offline1\030\006 \001(\0132\013.OfflineMs"
  "g\022\033\n\007online2\030\007 \001(\0132\n.OnlineMsg\022\035\n\010offlin"
  "e2\030\010 \001(\0132\013.OfflineMsgb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_hmiMsg_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_hmiMsg_2eproto_sccs[6] = {
  &scc_info_HeaderMsg_hmiMsg_2eproto.base,
  &scc_info_HmiConfigMsg_hmiMsg_2eproto.base,
  &scc_info_HmiMsg_hmiMsg_2eproto.base,
  &scc_info_OfflineMsg_hmiMsg_2eproto.base,
  &scc_info_OnlineMsg_hmiMsg_2eproto.base,
  &scc_info_SMBMsg_hmiMsg_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_hmiMsg_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_hmiMsg_2eproto = {
  false, false, descriptor_table_protodef_hmiMsg_2eproto, "hmiMsg.proto", 869,
  &descriptor_table_hmiMsg_2eproto_once, descriptor_table_hmiMsg_2eproto_sccs, descriptor_table_hmiMsg_2eproto_deps, 6, 0,
  schemas, file_default_instances, TableStruct_hmiMsg_2eproto::offsets,
  file_level_metadata_hmiMsg_2eproto, 6, file_level_enum_descriptors_hmiMsg_2eproto, file_level_service_descriptors_hmiMsg_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_hmiMsg_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_hmiMsg_2eproto)), true);

// ===================================================================

void HeaderMsg::InitAsDefaultInstance() {
}
class HeaderMsg::_Internal {
 public:
};

HeaderMsg::HeaderMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:HeaderMsg)
}
HeaderMsg::HeaderMsg(const HeaderMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  version_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_version().empty()) {
    version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_version(),
      GetArena());
  }
  timestamp_ = from.timestamp_;
  // @@protoc_insertion_point(copy_constructor:HeaderMsg)
}

void HeaderMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_HeaderMsg_hmiMsg_2eproto.base);
  version_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  timestamp_ = PROTOBUF_ULONGLONG(0);
}

HeaderMsg::~HeaderMsg() {
  // @@protoc_insertion_point(destructor:HeaderMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void HeaderMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  version_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void HeaderMsg::ArenaDtor(void* object) {
  HeaderMsg* _this = reinterpret_cast< HeaderMsg* >(object);
  (void)_this;
}
void HeaderMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void HeaderMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const HeaderMsg& HeaderMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_HeaderMsg_hmiMsg_2eproto.base);
  return *internal_default_instance();
}


void HeaderMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:HeaderMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  version_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  timestamp_ = PROTOBUF_ULONGLONG(0);
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HeaderMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_version();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "HeaderMsg.version"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* HeaderMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HeaderMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 timestamp = 1;
  if (this->timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_timestamp(), target);
  }

  // string version = 2;
  if (this->version().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_version().data(), static_cast<int>(this->_internal_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "HeaderMsg.version");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HeaderMsg)
  return target;
}

size_t HeaderMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HeaderMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string version = 2;
  if (this->version().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_version());
  }

  // uint64 timestamp = 1;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_timestamp());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HeaderMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HeaderMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const HeaderMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<HeaderMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HeaderMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HeaderMsg)
    MergeFrom(*source);
  }
}

void HeaderMsg::MergeFrom(const HeaderMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HeaderMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.version().size() > 0) {
    _internal_set_version(from._internal_version());
  }
  if (from.timestamp() != 0) {
    _internal_set_timestamp(from._internal_timestamp());
  }
}

void HeaderMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HeaderMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HeaderMsg::CopyFrom(const HeaderMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HeaderMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeaderMsg::IsInitialized() const {
  return true;
}

void HeaderMsg::InternalSwap(HeaderMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  version_.Swap(&other->version_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(timestamp_, other->timestamp_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HeaderMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SMBMsg::InitAsDefaultInstance() {
}
class SMBMsg::_Internal {
 public:
};

SMBMsg::SMBMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:SMBMsg)
}
SMBMsg::SMBMsg(const SMBMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&smb_id_, &from.smb_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&tmp_) -
    reinterpret_cast<char*>(&smb_id_)) + sizeof(tmp_));
  // @@protoc_insertion_point(copy_constructor:SMBMsg)
}

void SMBMsg::SharedCtor() {
  ::memset(&smb_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&tmp_) -
      reinterpret_cast<char*>(&smb_id_)) + sizeof(tmp_));
}

SMBMsg::~SMBMsg() {
  // @@protoc_insertion_point(destructor:SMBMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SMBMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SMBMsg::ArenaDtor(void* object) {
  SMBMsg* _this = reinterpret_cast< SMBMsg* >(object);
  (void)_this;
}
void SMBMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SMBMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SMBMsg& SMBMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SMBMsg_hmiMsg_2eproto.base);
  return *internal_default_instance();
}


void SMBMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:SMBMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&smb_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&tmp_) -
      reinterpret_cast<char*>(&smb_id_)) + sizeof(tmp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SMBMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 smb_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          smb_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 vol_10mV = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          vol_10mv_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 cur_10mA = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          cur_10ma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 soc = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          soc_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 tmp = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          tmp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SMBMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SMBMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 smb_id = 1;
  if (this->smb_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_smb_id(), target);
  }

  // uint32 vol_10mV = 2;
  if (this->vol_10mv() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_vol_10mv(), target);
  }

  // int32 cur_10mA = 3;
  if (this->cur_10ma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_cur_10ma(), target);
  }

  // uint32 soc = 4;
  if (this->soc() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_soc(), target);
  }

  // int32 tmp = 5;
  if (this->tmp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_tmp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SMBMsg)
  return target;
}

size_t SMBMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SMBMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 smb_id = 1;
  if (this->smb_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_smb_id());
  }

  // uint32 vol_10mV = 2;
  if (this->vol_10mv() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_vol_10mv());
  }

  // int32 cur_10mA = 3;
  if (this->cur_10ma() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_cur_10ma());
  }

  // uint32 soc = 4;
  if (this->soc() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_soc());
  }

  // int32 tmp = 5;
  if (this->tmp() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_tmp());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SMBMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SMBMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const SMBMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SMBMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SMBMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SMBMsg)
    MergeFrom(*source);
  }
}

void SMBMsg::MergeFrom(const SMBMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SMBMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.smb_id() != 0) {
    _internal_set_smb_id(from._internal_smb_id());
  }
  if (from.vol_10mv() != 0) {
    _internal_set_vol_10mv(from._internal_vol_10mv());
  }
  if (from.cur_10ma() != 0) {
    _internal_set_cur_10ma(from._internal_cur_10ma());
  }
  if (from.soc() != 0) {
    _internal_set_soc(from._internal_soc());
  }
  if (from.tmp() != 0) {
    _internal_set_tmp(from._internal_tmp());
  }
}

void SMBMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SMBMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SMBMsg::CopyFrom(const SMBMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SMBMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SMBMsg::IsInitialized() const {
  return true;
}

void SMBMsg::InternalSwap(SMBMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SMBMsg, tmp_)
      + sizeof(SMBMsg::tmp_)
      - PROTOBUF_FIELD_OFFSET(SMBMsg, smb_id_)>(
          reinterpret_cast<char*>(&smb_id_),
          reinterpret_cast<char*>(&other->smb_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SMBMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void HmiMsg::InitAsDefaultInstance() {
  ::_HmiMsg_default_instance_._instance.get_mutable()->header_ = const_cast< ::HeaderMsg*>(
      ::HeaderMsg::internal_default_instance());
}
class HmiMsg::_Internal {
 public:
  static const ::HeaderMsg& header(const HmiMsg* msg);
};

const ::HeaderMsg&
HmiMsg::_Internal::header(const HmiMsg* msg) {
  return *msg->header_;
}
HmiMsg::HmiMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  smb_infos_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:HmiMsg)
}
HmiMsg::HmiMsg(const HmiMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      smb_infos_(from.smb_infos_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_header()) {
    header_ = new ::HeaderMsg(*from.header_);
  } else {
    header_ = nullptr;
  }
  ::memcpy(&en_ctrl_start_, &from.en_ctrl_start_,
    static_cast<size_t>(reinterpret_cast<char*>(&pf_val_milli_) -
    reinterpret_cast<char*>(&en_ctrl_start_)) + sizeof(pf_val_milli_));
  // @@protoc_insertion_point(copy_constructor:HmiMsg)
}

void HmiMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_HmiMsg_hmiMsg_2eproto.base);
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&pf_val_milli_) -
      reinterpret_cast<char*>(&header_)) + sizeof(pf_val_milli_));
}

HmiMsg::~HmiMsg() {
  // @@protoc_insertion_point(destructor:HmiMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void HmiMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete header_;
}

void HmiMsg::ArenaDtor(void* object) {
  HmiMsg* _this = reinterpret_cast< HmiMsg* >(object);
  (void)_this;
}
void HmiMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void HmiMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const HmiMsg& HmiMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_HmiMsg_hmiMsg_2eproto.base);
  return *internal_default_instance();
}


void HmiMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:HmiMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  smb_infos_.Clear();
  if (GetArena() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
  ::memset(&en_ctrl_start_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&pf_val_milli_) -
      reinterpret_cast<char*>(&en_ctrl_start_)) + sizeof(pf_val_milli_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HmiMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .HeaderMsg header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 en_ctrl_start = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          en_ctrl_start_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 out_mode = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          out_mode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 dw_vol_mV = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          dw_vol_mv_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 dw_freq_mHz = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          dw_freq_mhz_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 dw_cur_mA = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          dw_cur_ma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 smb_vol_mV = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          smb_vol_mv_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 smb_cur_mA = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          smb_cur_ma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 smb_freq_mHz = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          smb_freq_mhz_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 smb_total_soc = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          smb_total_soc_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float smb_dw_phase_diff = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 93)) {
          smb_dw_phase_diff_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float pf_val_milli = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 101)) {
          pf_val_milli_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated .SMBMsg smb_infos = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_smb_infos(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<106>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* HmiMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HmiMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .HeaderMsg header = 1;
  if (this->has_header()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::header(this), target, stream);
  }

  // uint32 en_ctrl_start = 2;
  if (this->en_ctrl_start() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_en_ctrl_start(), target);
  }

  // uint32 out_mode = 3;
  if (this->out_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_out_mode(), target);
  }

  // uint32 dw_vol_mV = 4;
  if (this->dw_vol_mv() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_dw_vol_mv(), target);
  }

  // uint32 dw_freq_mHz = 5;
  if (this->dw_freq_mhz() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_dw_freq_mhz(), target);
  }

  // uint32 dw_cur_mA = 6;
  if (this->dw_cur_ma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_dw_cur_ma(), target);
  }

  // uint32 smb_vol_mV = 7;
  if (this->smb_vol_mv() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(7, this->_internal_smb_vol_mv(), target);
  }

  // uint32 smb_cur_mA = 8;
  if (this->smb_cur_ma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(8, this->_internal_smb_cur_ma(), target);
  }

  // uint32 smb_freq_mHz = 9;
  if (this->smb_freq_mhz() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(9, this->_internal_smb_freq_mhz(), target);
  }

  // uint32 smb_total_soc = 10;
  if (this->smb_total_soc() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(10, this->_internal_smb_total_soc(), target);
  }

  // float smb_dw_phase_diff = 11;
  if (!(this->smb_dw_phase_diff() <= 0 && this->smb_dw_phase_diff() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(11, this->_internal_smb_dw_phase_diff(), target);
  }

  // float pf_val_milli = 12;
  if (!(this->pf_val_milli() <= 0 && this->pf_val_milli() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(12, this->_internal_pf_val_milli(), target);
  }

  // repeated .SMBMsg smb_infos = 13;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_smb_infos_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(13, this->_internal_smb_infos(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HmiMsg)
  return target;
}

size_t HmiMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HmiMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .SMBMsg smb_infos = 13;
  total_size += 1UL * this->_internal_smb_infos_size();
  for (const auto& msg : this->smb_infos_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .HeaderMsg header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *header_);
  }

  // uint32 en_ctrl_start = 2;
  if (this->en_ctrl_start() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_en_ctrl_start());
  }

  // uint32 out_mode = 3;
  if (this->out_mode() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_out_mode());
  }

  // uint32 dw_vol_mV = 4;
  if (this->dw_vol_mv() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_dw_vol_mv());
  }

  // uint32 dw_freq_mHz = 5;
  if (this->dw_freq_mhz() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_dw_freq_mhz());
  }

  // uint32 dw_cur_mA = 6;
  if (this->dw_cur_ma() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_dw_cur_ma());
  }

  // uint32 smb_vol_mV = 7;
  if (this->smb_vol_mv() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_smb_vol_mv());
  }

  // uint32 smb_cur_mA = 8;
  if (this->smb_cur_ma() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_smb_cur_ma());
  }

  // uint32 smb_freq_mHz = 9;
  if (this->smb_freq_mhz() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_smb_freq_mhz());
  }

  // uint32 smb_total_soc = 10;
  if (this->smb_total_soc() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_smb_total_soc());
  }

  // float smb_dw_phase_diff = 11;
  if (!(this->smb_dw_phase_diff() <= 0 && this->smb_dw_phase_diff() >= 0)) {
    total_size += 1 + 4;
  }

  // float pf_val_milli = 12;
  if (!(this->pf_val_milli() <= 0 && this->pf_val_milli() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HmiMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HmiMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const HmiMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<HmiMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HmiMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HmiMsg)
    MergeFrom(*source);
  }
}

void HmiMsg::MergeFrom(const HmiMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HmiMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  smb_infos_.MergeFrom(from.smb_infos_);
  if (from.has_header()) {
    _internal_mutable_header()->::HeaderMsg::MergeFrom(from._internal_header());
  }
  if (from.en_ctrl_start() != 0) {
    _internal_set_en_ctrl_start(from._internal_en_ctrl_start());
  }
  if (from.out_mode() != 0) {
    _internal_set_out_mode(from._internal_out_mode());
  }
  if (from.dw_vol_mv() != 0) {
    _internal_set_dw_vol_mv(from._internal_dw_vol_mv());
  }
  if (from.dw_freq_mhz() != 0) {
    _internal_set_dw_freq_mhz(from._internal_dw_freq_mhz());
  }
  if (from.dw_cur_ma() != 0) {
    _internal_set_dw_cur_ma(from._internal_dw_cur_ma());
  }
  if (from.smb_vol_mv() != 0) {
    _internal_set_smb_vol_mv(from._internal_smb_vol_mv());
  }
  if (from.smb_cur_ma() != 0) {
    _internal_set_smb_cur_ma(from._internal_smb_cur_ma());
  }
  if (from.smb_freq_mhz() != 0) {
    _internal_set_smb_freq_mhz(from._internal_smb_freq_mhz());
  }
  if (from.smb_total_soc() != 0) {
    _internal_set_smb_total_soc(from._internal_smb_total_soc());
  }
  if (!(from.smb_dw_phase_diff() <= 0 && from.smb_dw_phase_diff() >= 0)) {
    _internal_set_smb_dw_phase_diff(from._internal_smb_dw_phase_diff());
  }
  if (!(from.pf_val_milli() <= 0 && from.pf_val_milli() >= 0)) {
    _internal_set_pf_val_milli(from._internal_pf_val_milli());
  }
}

void HmiMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HmiMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HmiMsg::CopyFrom(const HmiMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HmiMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HmiMsg::IsInitialized() const {
  return true;
}

void HmiMsg::InternalSwap(HmiMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  smb_infos_.InternalSwap(&other->smb_infos_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HmiMsg, pf_val_milli_)
      + sizeof(HmiMsg::pf_val_milli_)
      - PROTOBUF_FIELD_OFFSET(HmiMsg, header_)>(
          reinterpret_cast<char*>(&header_),
          reinterpret_cast<char*>(&other->header_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HmiMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void OnlineMsg::InitAsDefaultInstance() {
}
class OnlineMsg::_Internal {
 public:
};

OnlineMsg::OnlineMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:OnlineMsg)
}
OnlineMsg::OnlineMsg(const OnlineMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  start_time_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_start_time().empty()) {
    start_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_start_time(),
      GetArena());
  }
  end_time_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_end_time().empty()) {
    end_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_end_time(),
      GetArena());
  }
  cur_10ma_ = from.cur_10ma_;
  // @@protoc_insertion_point(copy_constructor:OnlineMsg)
}

void OnlineMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_OnlineMsg_hmiMsg_2eproto.base);
  start_time_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  end_time_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  cur_10ma_ = 0u;
}

OnlineMsg::~OnlineMsg() {
  // @@protoc_insertion_point(destructor:OnlineMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void OnlineMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  start_time_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  end_time_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void OnlineMsg::ArenaDtor(void* object) {
  OnlineMsg* _this = reinterpret_cast< OnlineMsg* >(object);
  (void)_this;
}
void OnlineMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void OnlineMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const OnlineMsg& OnlineMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_OnlineMsg_hmiMsg_2eproto.base);
  return *internal_default_instance();
}


void OnlineMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:OnlineMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  start_time_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  end_time_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  cur_10ma_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OnlineMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string start_time = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_start_time();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "OnlineMsg.start_time"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string end_time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_end_time();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "OnlineMsg.end_time"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 cur_10mA = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          cur_10ma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* OnlineMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OnlineMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string start_time = 1;
  if (this->start_time().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_start_time().data(), static_cast<int>(this->_internal_start_time().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OnlineMsg.start_time");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_start_time(), target);
  }

  // string end_time = 2;
  if (this->end_time().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_end_time().data(), static_cast<int>(this->_internal_end_time().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OnlineMsg.end_time");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_end_time(), target);
  }

  // uint32 cur_10mA = 3;
  if (this->cur_10ma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_cur_10ma(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OnlineMsg)
  return target;
}

size_t OnlineMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OnlineMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string start_time = 1;
  if (this->start_time().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_start_time());
  }

  // string end_time = 2;
  if (this->end_time().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_end_time());
  }

  // uint32 cur_10mA = 3;
  if (this->cur_10ma() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_cur_10ma());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OnlineMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OnlineMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const OnlineMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<OnlineMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OnlineMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OnlineMsg)
    MergeFrom(*source);
  }
}

void OnlineMsg::MergeFrom(const OnlineMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OnlineMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.start_time().size() > 0) {
    _internal_set_start_time(from._internal_start_time());
  }
  if (from.end_time().size() > 0) {
    _internal_set_end_time(from._internal_end_time());
  }
  if (from.cur_10ma() != 0) {
    _internal_set_cur_10ma(from._internal_cur_10ma());
  }
}

void OnlineMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OnlineMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OnlineMsg::CopyFrom(const OnlineMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OnlineMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OnlineMsg::IsInitialized() const {
  return true;
}

void OnlineMsg::InternalSwap(OnlineMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  start_time_.Swap(&other->start_time_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  end_time_.Swap(&other->end_time_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(cur_10ma_, other->cur_10ma_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OnlineMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void OfflineMsg::InitAsDefaultInstance() {
}
class OfflineMsg::_Internal {
 public:
};

OfflineMsg::OfflineMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:OfflineMsg)
}
OfflineMsg::OfflineMsg(const OfflineMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  start_time_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_start_time().empty()) {
    start_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_start_time(),
      GetArena());
  }
  end_time_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_end_time().empty()) {
    end_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_end_time(),
      GetArena());
  }
  ::memcpy(&vol_10ma_, &from.vol_10ma_,
    static_cast<size_t>(reinterpret_cast<char*>(&power_) -
    reinterpret_cast<char*>(&vol_10ma_)) + sizeof(power_));
  // @@protoc_insertion_point(copy_constructor:OfflineMsg)
}

void OfflineMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_OfflineMsg_hmiMsg_2eproto.base);
  start_time_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  end_time_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&vol_10ma_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&power_) -
      reinterpret_cast<char*>(&vol_10ma_)) + sizeof(power_));
}

OfflineMsg::~OfflineMsg() {
  // @@protoc_insertion_point(destructor:OfflineMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void OfflineMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  start_time_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  end_time_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void OfflineMsg::ArenaDtor(void* object) {
  OfflineMsg* _this = reinterpret_cast< OfflineMsg* >(object);
  (void)_this;
}
void OfflineMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void OfflineMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const OfflineMsg& OfflineMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_OfflineMsg_hmiMsg_2eproto.base);
  return *internal_default_instance();
}


void OfflineMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:OfflineMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  start_time_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  end_time_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&vol_10ma_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&power_) -
      reinterpret_cast<char*>(&vol_10ma_)) + sizeof(power_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OfflineMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string start_time = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_start_time();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "OfflineMsg.start_time"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string end_time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_end_time();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "OfflineMsg.end_time"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 vol_10mA = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          vol_10ma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 power = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          power_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* OfflineMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OfflineMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string start_time = 1;
  if (this->start_time().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_start_time().data(), static_cast<int>(this->_internal_start_time().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OfflineMsg.start_time");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_start_time(), target);
  }

  // string end_time = 2;
  if (this->end_time().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_end_time().data(), static_cast<int>(this->_internal_end_time().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "OfflineMsg.end_time");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_end_time(), target);
  }

  // uint32 vol_10mA = 3;
  if (this->vol_10ma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_vol_10ma(), target);
  }

  // uint32 power = 4;
  if (this->power() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_power(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OfflineMsg)
  return target;
}

size_t OfflineMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OfflineMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string start_time = 1;
  if (this->start_time().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_start_time());
  }

  // string end_time = 2;
  if (this->end_time().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_end_time());
  }

  // uint32 vol_10mA = 3;
  if (this->vol_10ma() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_vol_10ma());
  }

  // uint32 power = 4;
  if (this->power() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_power());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OfflineMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OfflineMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const OfflineMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<OfflineMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OfflineMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OfflineMsg)
    MergeFrom(*source);
  }
}

void OfflineMsg::MergeFrom(const OfflineMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OfflineMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.start_time().size() > 0) {
    _internal_set_start_time(from._internal_start_time());
  }
  if (from.end_time().size() > 0) {
    _internal_set_end_time(from._internal_end_time());
  }
  if (from.vol_10ma() != 0) {
    _internal_set_vol_10ma(from._internal_vol_10ma());
  }
  if (from.power() != 0) {
    _internal_set_power(from._internal_power());
  }
}

void OfflineMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OfflineMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OfflineMsg::CopyFrom(const OfflineMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OfflineMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OfflineMsg::IsInitialized() const {
  return true;
}

void OfflineMsg::InternalSwap(OfflineMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  start_time_.Swap(&other->start_time_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  end_time_.Swap(&other->end_time_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OfflineMsg, power_)
      + sizeof(OfflineMsg::power_)
      - PROTOBUF_FIELD_OFFSET(OfflineMsg, vol_10ma_)>(
          reinterpret_cast<char*>(&vol_10ma_),
          reinterpret_cast<char*>(&other->vol_10ma_));
}

::PROTOBUF_NAMESPACE_ID::Metadata OfflineMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void HmiConfigMsg::InitAsDefaultInstance() {
  ::_HmiConfigMsg_default_instance_._instance.get_mutable()->header_ = const_cast< ::HeaderMsg*>(
      ::HeaderMsg::internal_default_instance());
  ::_HmiConfigMsg_default_instance_._instance.get_mutable()->online1_ = const_cast< ::OnlineMsg*>(
      ::OnlineMsg::internal_default_instance());
  ::_HmiConfigMsg_default_instance_._instance.get_mutable()->offline1_ = const_cast< ::OfflineMsg*>(
      ::OfflineMsg::internal_default_instance());
  ::_HmiConfigMsg_default_instance_._instance.get_mutable()->online2_ = const_cast< ::OnlineMsg*>(
      ::OnlineMsg::internal_default_instance());
  ::_HmiConfigMsg_default_instance_._instance.get_mutable()->offline2_ = const_cast< ::OfflineMsg*>(
      ::OfflineMsg::internal_default_instance());
}
class HmiConfigMsg::_Internal {
 public:
  static const ::HeaderMsg& header(const HmiConfigMsg* msg);
  static const ::OnlineMsg& online1(const HmiConfigMsg* msg);
  static const ::OfflineMsg& offline1(const HmiConfigMsg* msg);
  static const ::OnlineMsg& online2(const HmiConfigMsg* msg);
  static const ::OfflineMsg& offline2(const HmiConfigMsg* msg);
};

const ::HeaderMsg&
HmiConfigMsg::_Internal::header(const HmiConfigMsg* msg) {
  return *msg->header_;
}
const ::OnlineMsg&
HmiConfigMsg::_Internal::online1(const HmiConfigMsg* msg) {
  return *msg->online1_;
}
const ::OfflineMsg&
HmiConfigMsg::_Internal::offline1(const HmiConfigMsg* msg) {
  return *msg->offline1_;
}
const ::OnlineMsg&
HmiConfigMsg::_Internal::online2(const HmiConfigMsg* msg) {
  return *msg->online2_;
}
const ::OfflineMsg&
HmiConfigMsg::_Internal::offline2(const HmiConfigMsg* msg) {
  return *msg->offline2_;
}
HmiConfigMsg::HmiConfigMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:HmiConfigMsg)
}
HmiConfigMsg::HmiConfigMsg(const HmiConfigMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_header()) {
    header_ = new ::HeaderMsg(*from.header_);
  } else {
    header_ = nullptr;
  }
  if (from._internal_has_online1()) {
    online1_ = new ::OnlineMsg(*from.online1_);
  } else {
    online1_ = nullptr;
  }
  if (from._internal_has_offline1()) {
    offline1_ = new ::OfflineMsg(*from.offline1_);
  } else {
    offline1_ = nullptr;
  }
  if (from._internal_has_online2()) {
    online2_ = new ::OnlineMsg(*from.online2_);
  } else {
    online2_ = nullptr;
  }
  if (from._internal_has_offline2()) {
    offline2_ = new ::OfflineMsg(*from.offline2_);
  } else {
    offline2_ = nullptr;
  }
  ::memcpy(&en_set_smb_chacur_10ma_, &from.en_set_smb_chacur_10ma_,
    static_cast<size_t>(reinterpret_cast<char*>(&set_smb_chacur_10ma_) -
    reinterpret_cast<char*>(&en_set_smb_chacur_10ma_)) + sizeof(set_smb_chacur_10ma_));
  // @@protoc_insertion_point(copy_constructor:HmiConfigMsg)
}

void HmiConfigMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_HmiConfigMsg_hmiMsg_2eproto.base);
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&set_smb_chacur_10ma_) -
      reinterpret_cast<char*>(&header_)) + sizeof(set_smb_chacur_10ma_));
}

HmiConfigMsg::~HmiConfigMsg() {
  // @@protoc_insertion_point(destructor:HmiConfigMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void HmiConfigMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete header_;
  if (this != internal_default_instance()) delete online1_;
  if (this != internal_default_instance()) delete offline1_;
  if (this != internal_default_instance()) delete online2_;
  if (this != internal_default_instance()) delete offline2_;
}

void HmiConfigMsg::ArenaDtor(void* object) {
  HmiConfigMsg* _this = reinterpret_cast< HmiConfigMsg* >(object);
  (void)_this;
}
void HmiConfigMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void HmiConfigMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const HmiConfigMsg& HmiConfigMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_HmiConfigMsg_hmiMsg_2eproto.base);
  return *internal_default_instance();
}


void HmiConfigMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:HmiConfigMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
  if (GetArena() == nullptr && online1_ != nullptr) {
    delete online1_;
  }
  online1_ = nullptr;
  if (GetArena() == nullptr && offline1_ != nullptr) {
    delete offline1_;
  }
  offline1_ = nullptr;
  if (GetArena() == nullptr && online2_ != nullptr) {
    delete online2_;
  }
  online2_ = nullptr;
  if (GetArena() == nullptr && offline2_ != nullptr) {
    delete offline2_;
  }
  offline2_ = nullptr;
  ::memset(&en_set_smb_chacur_10ma_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&set_smb_chacur_10ma_) -
      reinterpret_cast<char*>(&en_set_smb_chacur_10ma_)) + sizeof(set_smb_chacur_10ma_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HmiConfigMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .HeaderMsg header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool en_set_smb_chaCur_10mA = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          en_set_smb_chacur_10ma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 set_smb_disCur_10mA = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          set_smb_discur_10ma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 set_smb_chaCur_10mA = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          set_smb_chacur_10ma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .OnlineMsg online1 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_online1(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .OfflineMsg offline1 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_offline1(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .OnlineMsg online2 = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_online2(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .OfflineMsg offline2 = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_offline2(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* HmiConfigMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HmiConfigMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .HeaderMsg header = 1;
  if (this->has_header()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::header(this), target, stream);
  }

  // bool en_set_smb_chaCur_10mA = 2;
  if (this->en_set_smb_chacur_10ma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_en_set_smb_chacur_10ma(), target);
  }

  // uint32 set_smb_disCur_10mA = 3;
  if (this->set_smb_discur_10ma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_set_smb_discur_10ma(), target);
  }

  // uint32 set_smb_chaCur_10mA = 4;
  if (this->set_smb_chacur_10ma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_set_smb_chacur_10ma(), target);
  }

  // .OnlineMsg online1 = 5;
  if (this->has_online1()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::online1(this), target, stream);
  }

  // .OfflineMsg offline1 = 6;
  if (this->has_offline1()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::offline1(this), target, stream);
  }

  // .OnlineMsg online2 = 7;
  if (this->has_online2()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        7, _Internal::online2(this), target, stream);
  }

  // .OfflineMsg offline2 = 8;
  if (this->has_offline2()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        8, _Internal::offline2(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HmiConfigMsg)
  return target;
}

size_t HmiConfigMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HmiConfigMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .HeaderMsg header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *header_);
  }

  // .OnlineMsg online1 = 5;
  if (this->has_online1()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *online1_);
  }

  // .OfflineMsg offline1 = 6;
  if (this->has_offline1()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *offline1_);
  }

  // .OnlineMsg online2 = 7;
  if (this->has_online2()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *online2_);
  }

  // .OfflineMsg offline2 = 8;
  if (this->has_offline2()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *offline2_);
  }

  // bool en_set_smb_chaCur_10mA = 2;
  if (this->en_set_smb_chacur_10ma() != 0) {
    total_size += 1 + 1;
  }

  // uint32 set_smb_disCur_10mA = 3;
  if (this->set_smb_discur_10ma() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_set_smb_discur_10ma());
  }

  // uint32 set_smb_chaCur_10mA = 4;
  if (this->set_smb_chacur_10ma() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_set_smb_chacur_10ma());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HmiConfigMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HmiConfigMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const HmiConfigMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<HmiConfigMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HmiConfigMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HmiConfigMsg)
    MergeFrom(*source);
  }
}

void HmiConfigMsg::MergeFrom(const HmiConfigMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HmiConfigMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_header()) {
    _internal_mutable_header()->::HeaderMsg::MergeFrom(from._internal_header());
  }
  if (from.has_online1()) {
    _internal_mutable_online1()->::OnlineMsg::MergeFrom(from._internal_online1());
  }
  if (from.has_offline1()) {
    _internal_mutable_offline1()->::OfflineMsg::MergeFrom(from._internal_offline1());
  }
  if (from.has_online2()) {
    _internal_mutable_online2()->::OnlineMsg::MergeFrom(from._internal_online2());
  }
  if (from.has_offline2()) {
    _internal_mutable_offline2()->::OfflineMsg::MergeFrom(from._internal_offline2());
  }
  if (from.en_set_smb_chacur_10ma() != 0) {
    _internal_set_en_set_smb_chacur_10ma(from._internal_en_set_smb_chacur_10ma());
  }
  if (from.set_smb_discur_10ma() != 0) {
    _internal_set_set_smb_discur_10ma(from._internal_set_smb_discur_10ma());
  }
  if (from.set_smb_chacur_10ma() != 0) {
    _internal_set_set_smb_chacur_10ma(from._internal_set_smb_chacur_10ma());
  }
}

void HmiConfigMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HmiConfigMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HmiConfigMsg::CopyFrom(const HmiConfigMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HmiConfigMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HmiConfigMsg::IsInitialized() const {
  return true;
}

void HmiConfigMsg::InternalSwap(HmiConfigMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HmiConfigMsg, set_smb_chacur_10ma_)
      + sizeof(HmiConfigMsg::set_smb_chacur_10ma_)
      - PROTOBUF_FIELD_OFFSET(HmiConfigMsg, header_)>(
          reinterpret_cast<char*>(&header_),
          reinterpret_cast<char*>(&other->header_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HmiConfigMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::HeaderMsg* Arena::CreateMaybeMessage< ::HeaderMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HeaderMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::SMBMsg* Arena::CreateMaybeMessage< ::SMBMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SMBMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::HmiMsg* Arena::CreateMaybeMessage< ::HmiMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HmiMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::OnlineMsg* Arena::CreateMaybeMessage< ::OnlineMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OnlineMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::OfflineMsg* Arena::CreateMaybeMessage< ::OfflineMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OfflineMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::HmiConfigMsg* Arena::CreateMaybeMessage< ::HmiConfigMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HmiConfigMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
