// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hmiMsg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_hmiMsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_hmiMsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_hmiMsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_hmiMsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_hmiMsg_2eproto;
class HeaderMsg;
class HeaderMsgDefaultTypeInternal;
extern HeaderMsgDefaultTypeInternal _HeaderMsg_default_instance_;
class HmiConfigMsg;
class HmiConfigMsgDefaultTypeInternal;
extern HmiConfigMsgDefaultTypeInternal _HmiConfigMsg_default_instance_;
class HmiMsg;
class HmiMsgDefaultTypeInternal;
extern HmiMsgDefaultTypeInternal _HmiMsg_default_instance_;
class OfflineMsg;
class OfflineMsgDefaultTypeInternal;
extern OfflineMsgDefaultTypeInternal _OfflineMsg_default_instance_;
class OnlineMsg;
class OnlineMsgDefaultTypeInternal;
extern OnlineMsgDefaultTypeInternal _OnlineMsg_default_instance_;
class SMBMsg;
class SMBMsgDefaultTypeInternal;
extern SMBMsgDefaultTypeInternal _SMBMsg_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::HeaderMsg* Arena::CreateMaybeMessage<::HeaderMsg>(Arena*);
template<> ::HmiConfigMsg* Arena::CreateMaybeMessage<::HmiConfigMsg>(Arena*);
template<> ::HmiMsg* Arena::CreateMaybeMessage<::HmiMsg>(Arena*);
template<> ::OfflineMsg* Arena::CreateMaybeMessage<::OfflineMsg>(Arena*);
template<> ::OnlineMsg* Arena::CreateMaybeMessage<::OnlineMsg>(Arena*);
template<> ::SMBMsg* Arena::CreateMaybeMessage<::SMBMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class HeaderMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HeaderMsg) */ {
 public:
  inline HeaderMsg() : HeaderMsg(nullptr) {};
  virtual ~HeaderMsg();

  HeaderMsg(const HeaderMsg& from);
  HeaderMsg(HeaderMsg&& from) noexcept
    : HeaderMsg() {
    *this = ::std::move(from);
  }

  inline HeaderMsg& operator=(const HeaderMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeaderMsg& operator=(HeaderMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const HeaderMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HeaderMsg* internal_default_instance() {
    return reinterpret_cast<const HeaderMsg*>(
               &_HeaderMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HeaderMsg& a, HeaderMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(HeaderMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeaderMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline HeaderMsg* New() const final {
    return CreateMaybeMessage<HeaderMsg>(nullptr);
  }

  HeaderMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<HeaderMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const HeaderMsg& from);
  void MergeFrom(const HeaderMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeaderMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HeaderMsg";
  }
  protected:
  explicit HeaderMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hmiMsg_2eproto);
    return ::descriptor_table_hmiMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVersionFieldNumber = 2,
    kTimestampFieldNumber = 1,
  };
  // string version = 2;
  void clear_version();
  const std::string& version() const;
  void set_version(const std::string& value);
  void set_version(std::string&& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  std::string* mutable_version();
  std::string* release_version();
  void set_allocated_version(std::string* version);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_version();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_version(
      std::string* version);
  private:
  const std::string& _internal_version() const;
  void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // uint64 timestamp = 1;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:HeaderMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hmiMsg_2eproto;
};
// -------------------------------------------------------------------

class SMBMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SMBMsg) */ {
 public:
  inline SMBMsg() : SMBMsg(nullptr) {};
  virtual ~SMBMsg();

  SMBMsg(const SMBMsg& from);
  SMBMsg(SMBMsg&& from) noexcept
    : SMBMsg() {
    *this = ::std::move(from);
  }

  inline SMBMsg& operator=(const SMBMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline SMBMsg& operator=(SMBMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SMBMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SMBMsg* internal_default_instance() {
    return reinterpret_cast<const SMBMsg*>(
               &_SMBMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SMBMsg& a, SMBMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(SMBMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SMBMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SMBMsg* New() const final {
    return CreateMaybeMessage<SMBMsg>(nullptr);
  }

  SMBMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SMBMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SMBMsg& from);
  void MergeFrom(const SMBMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SMBMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SMBMsg";
  }
  protected:
  explicit SMBMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hmiMsg_2eproto);
    return ::descriptor_table_hmiMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSmbIdFieldNumber = 1,
    kVol10MVFieldNumber = 2,
    kCur10MAFieldNumber = 3,
    kSocFieldNumber = 4,
    kTmpFieldNumber = 5,
  };
  // uint32 smb_id = 1;
  void clear_smb_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 smb_id() const;
  void set_smb_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_smb_id() const;
  void _internal_set_smb_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 vol_10mV = 2;
  void clear_vol_10mv();
  ::PROTOBUF_NAMESPACE_ID::uint32 vol_10mv() const;
  void set_vol_10mv(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_vol_10mv() const;
  void _internal_set_vol_10mv(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // int32 cur_10mA = 3;
  void clear_cur_10ma();
  ::PROTOBUF_NAMESPACE_ID::int32 cur_10ma() const;
  void set_cur_10ma(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_cur_10ma() const;
  void _internal_set_cur_10ma(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // uint32 soc = 4;
  void clear_soc();
  ::PROTOBUF_NAMESPACE_ID::uint32 soc() const;
  void set_soc(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_soc() const;
  void _internal_set_soc(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // int32 tmp = 5;
  void clear_tmp();
  ::PROTOBUF_NAMESPACE_ID::int32 tmp() const;
  void set_tmp(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_tmp() const;
  void _internal_set_tmp(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:SMBMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 smb_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 vol_10mv_;
  ::PROTOBUF_NAMESPACE_ID::int32 cur_10ma_;
  ::PROTOBUF_NAMESPACE_ID::uint32 soc_;
  ::PROTOBUF_NAMESPACE_ID::int32 tmp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hmiMsg_2eproto;
};
// -------------------------------------------------------------------

class HmiMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HmiMsg) */ {
 public:
  inline HmiMsg() : HmiMsg(nullptr) {};
  virtual ~HmiMsg();

  HmiMsg(const HmiMsg& from);
  HmiMsg(HmiMsg&& from) noexcept
    : HmiMsg() {
    *this = ::std::move(from);
  }

  inline HmiMsg& operator=(const HmiMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline HmiMsg& operator=(HmiMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const HmiMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HmiMsg* internal_default_instance() {
    return reinterpret_cast<const HmiMsg*>(
               &_HmiMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(HmiMsg& a, HmiMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(HmiMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HmiMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline HmiMsg* New() const final {
    return CreateMaybeMessage<HmiMsg>(nullptr);
  }

  HmiMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<HmiMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const HmiMsg& from);
  void MergeFrom(const HmiMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HmiMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HmiMsg";
  }
  protected:
  explicit HmiMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hmiMsg_2eproto);
    return ::descriptor_table_hmiMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSmbInfosFieldNumber = 13,
    kHeaderFieldNumber = 1,
    kEnCtrlStartFieldNumber = 2,
    kOutModeFieldNumber = 3,
    kDwVolMVFieldNumber = 4,
    kDwFreqMHzFieldNumber = 5,
    kDwCurMAFieldNumber = 6,
    kSmbVolMVFieldNumber = 7,
    kSmbCurMAFieldNumber = 8,
    kSmbFreqMHzFieldNumber = 9,
    kSmbTotalSocFieldNumber = 10,
    kSmbDwPhaseDiffFieldNumber = 11,
    kPfValMilliFieldNumber = 12,
  };
  // repeated .SMBMsg smb_infos = 13;
  int smb_infos_size() const;
  private:
  int _internal_smb_infos_size() const;
  public:
  void clear_smb_infos();
  ::SMBMsg* mutable_smb_infos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SMBMsg >*
      mutable_smb_infos();
  private:
  const ::SMBMsg& _internal_smb_infos(int index) const;
  ::SMBMsg* _internal_add_smb_infos();
  public:
  const ::SMBMsg& smb_infos(int index) const;
  ::SMBMsg* add_smb_infos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SMBMsg >&
      smb_infos() const;

  // .HeaderMsg header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::HeaderMsg& header() const;
  ::HeaderMsg* release_header();
  ::HeaderMsg* mutable_header();
  void set_allocated_header(::HeaderMsg* header);
  private:
  const ::HeaderMsg& _internal_header() const;
  ::HeaderMsg* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::HeaderMsg* header);
  ::HeaderMsg* unsafe_arena_release_header();

  // uint32 en_ctrl_start = 2;
  void clear_en_ctrl_start();
  ::PROTOBUF_NAMESPACE_ID::uint32 en_ctrl_start() const;
  void set_en_ctrl_start(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_en_ctrl_start() const;
  void _internal_set_en_ctrl_start(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 out_mode = 3;
  void clear_out_mode();
  ::PROTOBUF_NAMESPACE_ID::uint32 out_mode() const;
  void set_out_mode(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_out_mode() const;
  void _internal_set_out_mode(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 dw_vol_mV = 4;
  void clear_dw_vol_mv();
  ::PROTOBUF_NAMESPACE_ID::uint32 dw_vol_mv() const;
  void set_dw_vol_mv(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_dw_vol_mv() const;
  void _internal_set_dw_vol_mv(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 dw_freq_mHz = 5;
  void clear_dw_freq_mhz();
  ::PROTOBUF_NAMESPACE_ID::uint32 dw_freq_mhz() const;
  void set_dw_freq_mhz(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_dw_freq_mhz() const;
  void _internal_set_dw_freq_mhz(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 dw_cur_mA = 6;
  void clear_dw_cur_ma();
  ::PROTOBUF_NAMESPACE_ID::uint32 dw_cur_ma() const;
  void set_dw_cur_ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_dw_cur_ma() const;
  void _internal_set_dw_cur_ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 smb_vol_mV = 7;
  void clear_smb_vol_mv();
  ::PROTOBUF_NAMESPACE_ID::uint32 smb_vol_mv() const;
  void set_smb_vol_mv(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_smb_vol_mv() const;
  void _internal_set_smb_vol_mv(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 smb_cur_mA = 8;
  void clear_smb_cur_ma();
  ::PROTOBUF_NAMESPACE_ID::uint32 smb_cur_ma() const;
  void set_smb_cur_ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_smb_cur_ma() const;
  void _internal_set_smb_cur_ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 smb_freq_mHz = 9;
  void clear_smb_freq_mhz();
  ::PROTOBUF_NAMESPACE_ID::uint32 smb_freq_mhz() const;
  void set_smb_freq_mhz(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_smb_freq_mhz() const;
  void _internal_set_smb_freq_mhz(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 smb_total_soc = 10;
  void clear_smb_total_soc();
  ::PROTOBUF_NAMESPACE_ID::uint32 smb_total_soc() const;
  void set_smb_total_soc(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_smb_total_soc() const;
  void _internal_set_smb_total_soc(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float smb_dw_phase_diff = 11;
  void clear_smb_dw_phase_diff();
  float smb_dw_phase_diff() const;
  void set_smb_dw_phase_diff(float value);
  private:
  float _internal_smb_dw_phase_diff() const;
  void _internal_set_smb_dw_phase_diff(float value);
  public:

  // float pf_val_milli = 12;
  void clear_pf_val_milli();
  float pf_val_milli() const;
  void set_pf_val_milli(float value);
  private:
  float _internal_pf_val_milli() const;
  void _internal_set_pf_val_milli(float value);
  public:

  // @@protoc_insertion_point(class_scope:HmiMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SMBMsg > smb_infos_;
  ::HeaderMsg* header_;
  ::PROTOBUF_NAMESPACE_ID::uint32 en_ctrl_start_;
  ::PROTOBUF_NAMESPACE_ID::uint32 out_mode_;
  ::PROTOBUF_NAMESPACE_ID::uint32 dw_vol_mv_;
  ::PROTOBUF_NAMESPACE_ID::uint32 dw_freq_mhz_;
  ::PROTOBUF_NAMESPACE_ID::uint32 dw_cur_ma_;
  ::PROTOBUF_NAMESPACE_ID::uint32 smb_vol_mv_;
  ::PROTOBUF_NAMESPACE_ID::uint32 smb_cur_ma_;
  ::PROTOBUF_NAMESPACE_ID::uint32 smb_freq_mhz_;
  ::PROTOBUF_NAMESPACE_ID::uint32 smb_total_soc_;
  float smb_dw_phase_diff_;
  float pf_val_milli_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hmiMsg_2eproto;
};
// -------------------------------------------------------------------

class OnlineMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:OnlineMsg) */ {
 public:
  inline OnlineMsg() : OnlineMsg(nullptr) {};
  virtual ~OnlineMsg();

  OnlineMsg(const OnlineMsg& from);
  OnlineMsg(OnlineMsg&& from) noexcept
    : OnlineMsg() {
    *this = ::std::move(from);
  }

  inline OnlineMsg& operator=(const OnlineMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline OnlineMsg& operator=(OnlineMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OnlineMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OnlineMsg* internal_default_instance() {
    return reinterpret_cast<const OnlineMsg*>(
               &_OnlineMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(OnlineMsg& a, OnlineMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(OnlineMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OnlineMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OnlineMsg* New() const final {
    return CreateMaybeMessage<OnlineMsg>(nullptr);
  }

  OnlineMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OnlineMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OnlineMsg& from);
  void MergeFrom(const OnlineMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OnlineMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "OnlineMsg";
  }
  protected:
  explicit OnlineMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hmiMsg_2eproto);
    return ::descriptor_table_hmiMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartTimeFieldNumber = 1,
    kEndTimeFieldNumber = 2,
    kCur10MAFieldNumber = 3,
  };
  // string start_time = 1;
  void clear_start_time();
  const std::string& start_time() const;
  void set_start_time(const std::string& value);
  void set_start_time(std::string&& value);
  void set_start_time(const char* value);
  void set_start_time(const char* value, size_t size);
  std::string* mutable_start_time();
  std::string* release_start_time();
  void set_allocated_start_time(std::string* start_time);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_start_time();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_start_time(
      std::string* start_time);
  private:
  const std::string& _internal_start_time() const;
  void _internal_set_start_time(const std::string& value);
  std::string* _internal_mutable_start_time();
  public:

  // string end_time = 2;
  void clear_end_time();
  const std::string& end_time() const;
  void set_end_time(const std::string& value);
  void set_end_time(std::string&& value);
  void set_end_time(const char* value);
  void set_end_time(const char* value, size_t size);
  std::string* mutable_end_time();
  std::string* release_end_time();
  void set_allocated_end_time(std::string* end_time);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_end_time();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_end_time(
      std::string* end_time);
  private:
  const std::string& _internal_end_time() const;
  void _internal_set_end_time(const std::string& value);
  std::string* _internal_mutable_end_time();
  public:

  // uint32 cur_10mA = 3;
  void clear_cur_10ma();
  ::PROTOBUF_NAMESPACE_ID::uint32 cur_10ma() const;
  void set_cur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_cur_10ma() const;
  void _internal_set_cur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:OnlineMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr start_time_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr end_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cur_10ma_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hmiMsg_2eproto;
};
// -------------------------------------------------------------------

class OfflineMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:OfflineMsg) */ {
 public:
  inline OfflineMsg() : OfflineMsg(nullptr) {};
  virtual ~OfflineMsg();

  OfflineMsg(const OfflineMsg& from);
  OfflineMsg(OfflineMsg&& from) noexcept
    : OfflineMsg() {
    *this = ::std::move(from);
  }

  inline OfflineMsg& operator=(const OfflineMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline OfflineMsg& operator=(OfflineMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OfflineMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OfflineMsg* internal_default_instance() {
    return reinterpret_cast<const OfflineMsg*>(
               &_OfflineMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(OfflineMsg& a, OfflineMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(OfflineMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OfflineMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OfflineMsg* New() const final {
    return CreateMaybeMessage<OfflineMsg>(nullptr);
  }

  OfflineMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OfflineMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OfflineMsg& from);
  void MergeFrom(const OfflineMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OfflineMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "OfflineMsg";
  }
  protected:
  explicit OfflineMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hmiMsg_2eproto);
    return ::descriptor_table_hmiMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartTimeFieldNumber = 1,
    kEndTimeFieldNumber = 2,
    kVol10MAFieldNumber = 3,
    kPowerFieldNumber = 4,
  };
  // string start_time = 1;
  void clear_start_time();
  const std::string& start_time() const;
  void set_start_time(const std::string& value);
  void set_start_time(std::string&& value);
  void set_start_time(const char* value);
  void set_start_time(const char* value, size_t size);
  std::string* mutable_start_time();
  std::string* release_start_time();
  void set_allocated_start_time(std::string* start_time);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_start_time();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_start_time(
      std::string* start_time);
  private:
  const std::string& _internal_start_time() const;
  void _internal_set_start_time(const std::string& value);
  std::string* _internal_mutable_start_time();
  public:

  // string end_time = 2;
  void clear_end_time();
  const std::string& end_time() const;
  void set_end_time(const std::string& value);
  void set_end_time(std::string&& value);
  void set_end_time(const char* value);
  void set_end_time(const char* value, size_t size);
  std::string* mutable_end_time();
  std::string* release_end_time();
  void set_allocated_end_time(std::string* end_time);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_end_time();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_end_time(
      std::string* end_time);
  private:
  const std::string& _internal_end_time() const;
  void _internal_set_end_time(const std::string& value);
  std::string* _internal_mutable_end_time();
  public:

  // uint32 vol_10mA = 3;
  void clear_vol_10ma();
  ::PROTOBUF_NAMESPACE_ID::uint32 vol_10ma() const;
  void set_vol_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_vol_10ma() const;
  void _internal_set_vol_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 power = 4;
  void clear_power();
  ::PROTOBUF_NAMESPACE_ID::uint32 power() const;
  void set_power(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_power() const;
  void _internal_set_power(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:OfflineMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr start_time_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr end_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 vol_10ma_;
  ::PROTOBUF_NAMESPACE_ID::uint32 power_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hmiMsg_2eproto;
};
// -------------------------------------------------------------------

class HmiConfigMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HmiConfigMsg) */ {
 public:
  inline HmiConfigMsg() : HmiConfigMsg(nullptr) {};
  virtual ~HmiConfigMsg();

  HmiConfigMsg(const HmiConfigMsg& from);
  HmiConfigMsg(HmiConfigMsg&& from) noexcept
    : HmiConfigMsg() {
    *this = ::std::move(from);
  }

  inline HmiConfigMsg& operator=(const HmiConfigMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline HmiConfigMsg& operator=(HmiConfigMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const HmiConfigMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HmiConfigMsg* internal_default_instance() {
    return reinterpret_cast<const HmiConfigMsg*>(
               &_HmiConfigMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(HmiConfigMsg& a, HmiConfigMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(HmiConfigMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HmiConfigMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline HmiConfigMsg* New() const final {
    return CreateMaybeMessage<HmiConfigMsg>(nullptr);
  }

  HmiConfigMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<HmiConfigMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const HmiConfigMsg& from);
  void MergeFrom(const HmiConfigMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HmiConfigMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HmiConfigMsg";
  }
  protected:
  explicit HmiConfigMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hmiMsg_2eproto);
    return ::descriptor_table_hmiMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kOnline1FieldNumber = 5,
    kOffline1FieldNumber = 6,
    kOnline2FieldNumber = 7,
    kOffline2FieldNumber = 8,
    kEnSetSmbChaCur10MAFieldNumber = 2,
    kSetSmbDisCur10MAFieldNumber = 3,
    kSetSmbChaCur10MAFieldNumber = 4,
  };
  // .HeaderMsg header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::HeaderMsg& header() const;
  ::HeaderMsg* release_header();
  ::HeaderMsg* mutable_header();
  void set_allocated_header(::HeaderMsg* header);
  private:
  const ::HeaderMsg& _internal_header() const;
  ::HeaderMsg* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::HeaderMsg* header);
  ::HeaderMsg* unsafe_arena_release_header();

  // .OnlineMsg online1 = 5;
  bool has_online1() const;
  private:
  bool _internal_has_online1() const;
  public:
  void clear_online1();
  const ::OnlineMsg& online1() const;
  ::OnlineMsg* release_online1();
  ::OnlineMsg* mutable_online1();
  void set_allocated_online1(::OnlineMsg* online1);
  private:
  const ::OnlineMsg& _internal_online1() const;
  ::OnlineMsg* _internal_mutable_online1();
  public:
  void unsafe_arena_set_allocated_online1(
      ::OnlineMsg* online1);
  ::OnlineMsg* unsafe_arena_release_online1();

  // .OfflineMsg offline1 = 6;
  bool has_offline1() const;
  private:
  bool _internal_has_offline1() const;
  public:
  void clear_offline1();
  const ::OfflineMsg& offline1() const;
  ::OfflineMsg* release_offline1();
  ::OfflineMsg* mutable_offline1();
  void set_allocated_offline1(::OfflineMsg* offline1);
  private:
  const ::OfflineMsg& _internal_offline1() const;
  ::OfflineMsg* _internal_mutable_offline1();
  public:
  void unsafe_arena_set_allocated_offline1(
      ::OfflineMsg* offline1);
  ::OfflineMsg* unsafe_arena_release_offline1();

  // .OnlineMsg online2 = 7;
  bool has_online2() const;
  private:
  bool _internal_has_online2() const;
  public:
  void clear_online2();
  const ::OnlineMsg& online2() const;
  ::OnlineMsg* release_online2();
  ::OnlineMsg* mutable_online2();
  void set_allocated_online2(::OnlineMsg* online2);
  private:
  const ::OnlineMsg& _internal_online2() const;
  ::OnlineMsg* _internal_mutable_online2();
  public:
  void unsafe_arena_set_allocated_online2(
      ::OnlineMsg* online2);
  ::OnlineMsg* unsafe_arena_release_online2();

  // .OfflineMsg offline2 = 8;
  bool has_offline2() const;
  private:
  bool _internal_has_offline2() const;
  public:
  void clear_offline2();
  const ::OfflineMsg& offline2() const;
  ::OfflineMsg* release_offline2();
  ::OfflineMsg* mutable_offline2();
  void set_allocated_offline2(::OfflineMsg* offline2);
  private:
  const ::OfflineMsg& _internal_offline2() const;
  ::OfflineMsg* _internal_mutable_offline2();
  public:
  void unsafe_arena_set_allocated_offline2(
      ::OfflineMsg* offline2);
  ::OfflineMsg* unsafe_arena_release_offline2();

  // bool en_set_smb_chaCur_10mA = 2;
  void clear_en_set_smb_chacur_10ma();
  bool en_set_smb_chacur_10ma() const;
  void set_en_set_smb_chacur_10ma(bool value);
  private:
  bool _internal_en_set_smb_chacur_10ma() const;
  void _internal_set_en_set_smb_chacur_10ma(bool value);
  public:

  // uint32 set_smb_disCur_10mA = 3;
  void clear_set_smb_discur_10ma();
  ::PROTOBUF_NAMESPACE_ID::uint32 set_smb_discur_10ma() const;
  void set_set_smb_discur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_set_smb_discur_10ma() const;
  void _internal_set_set_smb_discur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 set_smb_chaCur_10mA = 4;
  void clear_set_smb_chacur_10ma();
  ::PROTOBUF_NAMESPACE_ID::uint32 set_smb_chacur_10ma() const;
  void set_set_smb_chacur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_set_smb_chacur_10ma() const;
  void _internal_set_set_smb_chacur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:HmiConfigMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::HeaderMsg* header_;
  ::OnlineMsg* online1_;
  ::OfflineMsg* offline1_;
  ::OnlineMsg* online2_;
  ::OfflineMsg* offline2_;
  bool en_set_smb_chacur_10ma_;
  ::PROTOBUF_NAMESPACE_ID::uint32 set_smb_discur_10ma_;
  ::PROTOBUF_NAMESPACE_ID::uint32 set_smb_chacur_10ma_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hmiMsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HeaderMsg

// uint64 timestamp = 1;
inline void HeaderMsg::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 HeaderMsg::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 HeaderMsg::timestamp() const {
  // @@protoc_insertion_point(field_get:HeaderMsg.timestamp)
  return _internal_timestamp();
}
inline void HeaderMsg::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  timestamp_ = value;
}
inline void HeaderMsg::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:HeaderMsg.timestamp)
}

// string version = 2;
inline void HeaderMsg::clear_version() {
  version_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& HeaderMsg::version() const {
  // @@protoc_insertion_point(field_get:HeaderMsg.version)
  return _internal_version();
}
inline void HeaderMsg::set_version(const std::string& value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:HeaderMsg.version)
}
inline std::string* HeaderMsg::mutable_version() {
  // @@protoc_insertion_point(field_mutable:HeaderMsg.version)
  return _internal_mutable_version();
}
inline const std::string& HeaderMsg::_internal_version() const {
  return version_.Get();
}
inline void HeaderMsg::_internal_set_version(const std::string& value) {
  
  version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void HeaderMsg::set_version(std::string&& value) {
  
  version_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:HeaderMsg.version)
}
inline void HeaderMsg::set_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:HeaderMsg.version)
}
inline void HeaderMsg::set_version(const char* value,
    size_t size) {
  
  version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:HeaderMsg.version)
}
inline std::string* HeaderMsg::_internal_mutable_version() {
  
  return version_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* HeaderMsg::release_version() {
  // @@protoc_insertion_point(field_release:HeaderMsg.version)
  return version_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void HeaderMsg::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  version_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), version,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:HeaderMsg.version)
}
inline std::string* HeaderMsg::unsafe_arena_release_version() {
  // @@protoc_insertion_point(field_unsafe_arena_release:HeaderMsg.version)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return version_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void HeaderMsg::unsafe_arena_set_allocated_version(
    std::string* version) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (version != nullptr) {
    
  } else {
    
  }
  version_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      version, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HeaderMsg.version)
}

// -------------------------------------------------------------------

// SMBMsg

// uint32 smb_id = 1;
inline void SMBMsg::clear_smb_id() {
  smb_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SMBMsg::_internal_smb_id() const {
  return smb_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SMBMsg::smb_id() const {
  // @@protoc_insertion_point(field_get:SMBMsg.smb_id)
  return _internal_smb_id();
}
inline void SMBMsg::_internal_set_smb_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  smb_id_ = value;
}
inline void SMBMsg::set_smb_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_smb_id(value);
  // @@protoc_insertion_point(field_set:SMBMsg.smb_id)
}

// uint32 vol_10mV = 2;
inline void SMBMsg::clear_vol_10mv() {
  vol_10mv_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SMBMsg::_internal_vol_10mv() const {
  return vol_10mv_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SMBMsg::vol_10mv() const {
  // @@protoc_insertion_point(field_get:SMBMsg.vol_10mV)
  return _internal_vol_10mv();
}
inline void SMBMsg::_internal_set_vol_10mv(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  vol_10mv_ = value;
}
inline void SMBMsg::set_vol_10mv(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_vol_10mv(value);
  // @@protoc_insertion_point(field_set:SMBMsg.vol_10mV)
}

// int32 cur_10mA = 3;
inline void SMBMsg::clear_cur_10ma() {
  cur_10ma_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SMBMsg::_internal_cur_10ma() const {
  return cur_10ma_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SMBMsg::cur_10ma() const {
  // @@protoc_insertion_point(field_get:SMBMsg.cur_10mA)
  return _internal_cur_10ma();
}
inline void SMBMsg::_internal_set_cur_10ma(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  cur_10ma_ = value;
}
inline void SMBMsg::set_cur_10ma(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_cur_10ma(value);
  // @@protoc_insertion_point(field_set:SMBMsg.cur_10mA)
}

// uint32 soc = 4;
inline void SMBMsg::clear_soc() {
  soc_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SMBMsg::_internal_soc() const {
  return soc_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SMBMsg::soc() const {
  // @@protoc_insertion_point(field_get:SMBMsg.soc)
  return _internal_soc();
}
inline void SMBMsg::_internal_set_soc(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  soc_ = value;
}
inline void SMBMsg::set_soc(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_soc(value);
  // @@protoc_insertion_point(field_set:SMBMsg.soc)
}

// int32 tmp = 5;
inline void SMBMsg::clear_tmp() {
  tmp_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SMBMsg::_internal_tmp() const {
  return tmp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SMBMsg::tmp() const {
  // @@protoc_insertion_point(field_get:SMBMsg.tmp)
  return _internal_tmp();
}
inline void SMBMsg::_internal_set_tmp(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  tmp_ = value;
}
inline void SMBMsg::set_tmp(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_tmp(value);
  // @@protoc_insertion_point(field_set:SMBMsg.tmp)
}

// -------------------------------------------------------------------

// HmiMsg

// .HeaderMsg header = 1;
inline bool HmiMsg::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool HmiMsg::has_header() const {
  return _internal_has_header();
}
inline void HmiMsg::clear_header() {
  if (GetArena() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::HeaderMsg& HmiMsg::_internal_header() const {
  const ::HeaderMsg* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::HeaderMsg*>(
      &::_HeaderMsg_default_instance_);
}
inline const ::HeaderMsg& HmiMsg::header() const {
  // @@protoc_insertion_point(field_get:HmiMsg.header)
  return _internal_header();
}
inline void HmiMsg::unsafe_arena_set_allocated_header(
    ::HeaderMsg* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HmiMsg.header)
}
inline ::HeaderMsg* HmiMsg::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::HeaderMsg* HmiMsg::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:HmiMsg.header)
  
  ::HeaderMsg* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::HeaderMsg* HmiMsg::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::HeaderMsg>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::HeaderMsg* HmiMsg::mutable_header() {
  // @@protoc_insertion_point(field_mutable:HmiMsg.header)
  return _internal_mutable_header();
}
inline void HmiMsg::set_allocated_header(::HeaderMsg* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:HmiMsg.header)
}

// uint32 en_ctrl_start = 2;
inline void HmiMsg::clear_en_ctrl_start() {
  en_ctrl_start_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::_internal_en_ctrl_start() const {
  return en_ctrl_start_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::en_ctrl_start() const {
  // @@protoc_insertion_point(field_get:HmiMsg.en_ctrl_start)
  return _internal_en_ctrl_start();
}
inline void HmiMsg::_internal_set_en_ctrl_start(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  en_ctrl_start_ = value;
}
inline void HmiMsg::set_en_ctrl_start(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_en_ctrl_start(value);
  // @@protoc_insertion_point(field_set:HmiMsg.en_ctrl_start)
}

// uint32 out_mode = 3;
inline void HmiMsg::clear_out_mode() {
  out_mode_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::_internal_out_mode() const {
  return out_mode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::out_mode() const {
  // @@protoc_insertion_point(field_get:HmiMsg.out_mode)
  return _internal_out_mode();
}
inline void HmiMsg::_internal_set_out_mode(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  out_mode_ = value;
}
inline void HmiMsg::set_out_mode(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_out_mode(value);
  // @@protoc_insertion_point(field_set:HmiMsg.out_mode)
}

// uint32 dw_vol_mV = 4;
inline void HmiMsg::clear_dw_vol_mv() {
  dw_vol_mv_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::_internal_dw_vol_mv() const {
  return dw_vol_mv_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::dw_vol_mv() const {
  // @@protoc_insertion_point(field_get:HmiMsg.dw_vol_mV)
  return _internal_dw_vol_mv();
}
inline void HmiMsg::_internal_set_dw_vol_mv(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  dw_vol_mv_ = value;
}
inline void HmiMsg::set_dw_vol_mv(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_dw_vol_mv(value);
  // @@protoc_insertion_point(field_set:HmiMsg.dw_vol_mV)
}

// uint32 dw_freq_mHz = 5;
inline void HmiMsg::clear_dw_freq_mhz() {
  dw_freq_mhz_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::_internal_dw_freq_mhz() const {
  return dw_freq_mhz_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::dw_freq_mhz() const {
  // @@protoc_insertion_point(field_get:HmiMsg.dw_freq_mHz)
  return _internal_dw_freq_mhz();
}
inline void HmiMsg::_internal_set_dw_freq_mhz(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  dw_freq_mhz_ = value;
}
inline void HmiMsg::set_dw_freq_mhz(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_dw_freq_mhz(value);
  // @@protoc_insertion_point(field_set:HmiMsg.dw_freq_mHz)
}

// uint32 dw_cur_mA = 6;
inline void HmiMsg::clear_dw_cur_ma() {
  dw_cur_ma_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::_internal_dw_cur_ma() const {
  return dw_cur_ma_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::dw_cur_ma() const {
  // @@protoc_insertion_point(field_get:HmiMsg.dw_cur_mA)
  return _internal_dw_cur_ma();
}
inline void HmiMsg::_internal_set_dw_cur_ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  dw_cur_ma_ = value;
}
inline void HmiMsg::set_dw_cur_ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_dw_cur_ma(value);
  // @@protoc_insertion_point(field_set:HmiMsg.dw_cur_mA)
}

// uint32 smb_vol_mV = 7;
inline void HmiMsg::clear_smb_vol_mv() {
  smb_vol_mv_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::_internal_smb_vol_mv() const {
  return smb_vol_mv_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::smb_vol_mv() const {
  // @@protoc_insertion_point(field_get:HmiMsg.smb_vol_mV)
  return _internal_smb_vol_mv();
}
inline void HmiMsg::_internal_set_smb_vol_mv(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  smb_vol_mv_ = value;
}
inline void HmiMsg::set_smb_vol_mv(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_smb_vol_mv(value);
  // @@protoc_insertion_point(field_set:HmiMsg.smb_vol_mV)
}

// uint32 smb_cur_mA = 8;
inline void HmiMsg::clear_smb_cur_ma() {
  smb_cur_ma_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::_internal_smb_cur_ma() const {
  return smb_cur_ma_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::smb_cur_ma() const {
  // @@protoc_insertion_point(field_get:HmiMsg.smb_cur_mA)
  return _internal_smb_cur_ma();
}
inline void HmiMsg::_internal_set_smb_cur_ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  smb_cur_ma_ = value;
}
inline void HmiMsg::set_smb_cur_ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_smb_cur_ma(value);
  // @@protoc_insertion_point(field_set:HmiMsg.smb_cur_mA)
}

// uint32 smb_freq_mHz = 9;
inline void HmiMsg::clear_smb_freq_mhz() {
  smb_freq_mhz_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::_internal_smb_freq_mhz() const {
  return smb_freq_mhz_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::smb_freq_mhz() const {
  // @@protoc_insertion_point(field_get:HmiMsg.smb_freq_mHz)
  return _internal_smb_freq_mhz();
}
inline void HmiMsg::_internal_set_smb_freq_mhz(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  smb_freq_mhz_ = value;
}
inline void HmiMsg::set_smb_freq_mhz(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_smb_freq_mhz(value);
  // @@protoc_insertion_point(field_set:HmiMsg.smb_freq_mHz)
}

// uint32 smb_total_soc = 10;
inline void HmiMsg::clear_smb_total_soc() {
  smb_total_soc_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::_internal_smb_total_soc() const {
  return smb_total_soc_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiMsg::smb_total_soc() const {
  // @@protoc_insertion_point(field_get:HmiMsg.smb_total_soc)
  return _internal_smb_total_soc();
}
inline void HmiMsg::_internal_set_smb_total_soc(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  smb_total_soc_ = value;
}
inline void HmiMsg::set_smb_total_soc(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_smb_total_soc(value);
  // @@protoc_insertion_point(field_set:HmiMsg.smb_total_soc)
}

// float smb_dw_phase_diff = 11;
inline void HmiMsg::clear_smb_dw_phase_diff() {
  smb_dw_phase_diff_ = 0;
}
inline float HmiMsg::_internal_smb_dw_phase_diff() const {
  return smb_dw_phase_diff_;
}
inline float HmiMsg::smb_dw_phase_diff() const {
  // @@protoc_insertion_point(field_get:HmiMsg.smb_dw_phase_diff)
  return _internal_smb_dw_phase_diff();
}
inline void HmiMsg::_internal_set_smb_dw_phase_diff(float value) {
  
  smb_dw_phase_diff_ = value;
}
inline void HmiMsg::set_smb_dw_phase_diff(float value) {
  _internal_set_smb_dw_phase_diff(value);
  // @@protoc_insertion_point(field_set:HmiMsg.smb_dw_phase_diff)
}

// float pf_val_milli = 12;
inline void HmiMsg::clear_pf_val_milli() {
  pf_val_milli_ = 0;
}
inline float HmiMsg::_internal_pf_val_milli() const {
  return pf_val_milli_;
}
inline float HmiMsg::pf_val_milli() const {
  // @@protoc_insertion_point(field_get:HmiMsg.pf_val_milli)
  return _internal_pf_val_milli();
}
inline void HmiMsg::_internal_set_pf_val_milli(float value) {
  
  pf_val_milli_ = value;
}
inline void HmiMsg::set_pf_val_milli(float value) {
  _internal_set_pf_val_milli(value);
  // @@protoc_insertion_point(field_set:HmiMsg.pf_val_milli)
}

// repeated .SMBMsg smb_infos = 13;
inline int HmiMsg::_internal_smb_infos_size() const {
  return smb_infos_.size();
}
inline int HmiMsg::smb_infos_size() const {
  return _internal_smb_infos_size();
}
inline void HmiMsg::clear_smb_infos() {
  smb_infos_.Clear();
}
inline ::SMBMsg* HmiMsg::mutable_smb_infos(int index) {
  // @@protoc_insertion_point(field_mutable:HmiMsg.smb_infos)
  return smb_infos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SMBMsg >*
HmiMsg::mutable_smb_infos() {
  // @@protoc_insertion_point(field_mutable_list:HmiMsg.smb_infos)
  return &smb_infos_;
}
inline const ::SMBMsg& HmiMsg::_internal_smb_infos(int index) const {
  return smb_infos_.Get(index);
}
inline const ::SMBMsg& HmiMsg::smb_infos(int index) const {
  // @@protoc_insertion_point(field_get:HmiMsg.smb_infos)
  return _internal_smb_infos(index);
}
inline ::SMBMsg* HmiMsg::_internal_add_smb_infos() {
  return smb_infos_.Add();
}
inline ::SMBMsg* HmiMsg::add_smb_infos() {
  // @@protoc_insertion_point(field_add:HmiMsg.smb_infos)
  return _internal_add_smb_infos();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SMBMsg >&
HmiMsg::smb_infos() const {
  // @@protoc_insertion_point(field_list:HmiMsg.smb_infos)
  return smb_infos_;
}

// -------------------------------------------------------------------

// OnlineMsg

// string start_time = 1;
inline void OnlineMsg::clear_start_time() {
  start_time_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& OnlineMsg::start_time() const {
  // @@protoc_insertion_point(field_get:OnlineMsg.start_time)
  return _internal_start_time();
}
inline void OnlineMsg::set_start_time(const std::string& value) {
  _internal_set_start_time(value);
  // @@protoc_insertion_point(field_set:OnlineMsg.start_time)
}
inline std::string* OnlineMsg::mutable_start_time() {
  // @@protoc_insertion_point(field_mutable:OnlineMsg.start_time)
  return _internal_mutable_start_time();
}
inline const std::string& OnlineMsg::_internal_start_time() const {
  return start_time_.Get();
}
inline void OnlineMsg::_internal_set_start_time(const std::string& value) {
  
  start_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void OnlineMsg::set_start_time(std::string&& value) {
  
  start_time_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:OnlineMsg.start_time)
}
inline void OnlineMsg::set_start_time(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  start_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:OnlineMsg.start_time)
}
inline void OnlineMsg::set_start_time(const char* value,
    size_t size) {
  
  start_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:OnlineMsg.start_time)
}
inline std::string* OnlineMsg::_internal_mutable_start_time() {
  
  return start_time_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* OnlineMsg::release_start_time() {
  // @@protoc_insertion_point(field_release:OnlineMsg.start_time)
  return start_time_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void OnlineMsg::set_allocated_start_time(std::string* start_time) {
  if (start_time != nullptr) {
    
  } else {
    
  }
  start_time_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), start_time,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:OnlineMsg.start_time)
}
inline std::string* OnlineMsg::unsafe_arena_release_start_time() {
  // @@protoc_insertion_point(field_unsafe_arena_release:OnlineMsg.start_time)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return start_time_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void OnlineMsg::unsafe_arena_set_allocated_start_time(
    std::string* start_time) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (start_time != nullptr) {
    
  } else {
    
  }
  start_time_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      start_time, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:OnlineMsg.start_time)
}

// string end_time = 2;
inline void OnlineMsg::clear_end_time() {
  end_time_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& OnlineMsg::end_time() const {
  // @@protoc_insertion_point(field_get:OnlineMsg.end_time)
  return _internal_end_time();
}
inline void OnlineMsg::set_end_time(const std::string& value) {
  _internal_set_end_time(value);
  // @@protoc_insertion_point(field_set:OnlineMsg.end_time)
}
inline std::string* OnlineMsg::mutable_end_time() {
  // @@protoc_insertion_point(field_mutable:OnlineMsg.end_time)
  return _internal_mutable_end_time();
}
inline const std::string& OnlineMsg::_internal_end_time() const {
  return end_time_.Get();
}
inline void OnlineMsg::_internal_set_end_time(const std::string& value) {
  
  end_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void OnlineMsg::set_end_time(std::string&& value) {
  
  end_time_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:OnlineMsg.end_time)
}
inline void OnlineMsg::set_end_time(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  end_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:OnlineMsg.end_time)
}
inline void OnlineMsg::set_end_time(const char* value,
    size_t size) {
  
  end_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:OnlineMsg.end_time)
}
inline std::string* OnlineMsg::_internal_mutable_end_time() {
  
  return end_time_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* OnlineMsg::release_end_time() {
  // @@protoc_insertion_point(field_release:OnlineMsg.end_time)
  return end_time_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void OnlineMsg::set_allocated_end_time(std::string* end_time) {
  if (end_time != nullptr) {
    
  } else {
    
  }
  end_time_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), end_time,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:OnlineMsg.end_time)
}
inline std::string* OnlineMsg::unsafe_arena_release_end_time() {
  // @@protoc_insertion_point(field_unsafe_arena_release:OnlineMsg.end_time)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return end_time_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void OnlineMsg::unsafe_arena_set_allocated_end_time(
    std::string* end_time) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (end_time != nullptr) {
    
  } else {
    
  }
  end_time_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      end_time, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:OnlineMsg.end_time)
}

// uint32 cur_10mA = 3;
inline void OnlineMsg::clear_cur_10ma() {
  cur_10ma_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OnlineMsg::_internal_cur_10ma() const {
  return cur_10ma_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OnlineMsg::cur_10ma() const {
  // @@protoc_insertion_point(field_get:OnlineMsg.cur_10mA)
  return _internal_cur_10ma();
}
inline void OnlineMsg::_internal_set_cur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  cur_10ma_ = value;
}
inline void OnlineMsg::set_cur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_cur_10ma(value);
  // @@protoc_insertion_point(field_set:OnlineMsg.cur_10mA)
}

// -------------------------------------------------------------------

// OfflineMsg

// string start_time = 1;
inline void OfflineMsg::clear_start_time() {
  start_time_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& OfflineMsg::start_time() const {
  // @@protoc_insertion_point(field_get:OfflineMsg.start_time)
  return _internal_start_time();
}
inline void OfflineMsg::set_start_time(const std::string& value) {
  _internal_set_start_time(value);
  // @@protoc_insertion_point(field_set:OfflineMsg.start_time)
}
inline std::string* OfflineMsg::mutable_start_time() {
  // @@protoc_insertion_point(field_mutable:OfflineMsg.start_time)
  return _internal_mutable_start_time();
}
inline const std::string& OfflineMsg::_internal_start_time() const {
  return start_time_.Get();
}
inline void OfflineMsg::_internal_set_start_time(const std::string& value) {
  
  start_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void OfflineMsg::set_start_time(std::string&& value) {
  
  start_time_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:OfflineMsg.start_time)
}
inline void OfflineMsg::set_start_time(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  start_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:OfflineMsg.start_time)
}
inline void OfflineMsg::set_start_time(const char* value,
    size_t size) {
  
  start_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:OfflineMsg.start_time)
}
inline std::string* OfflineMsg::_internal_mutable_start_time() {
  
  return start_time_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* OfflineMsg::release_start_time() {
  // @@protoc_insertion_point(field_release:OfflineMsg.start_time)
  return start_time_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void OfflineMsg::set_allocated_start_time(std::string* start_time) {
  if (start_time != nullptr) {
    
  } else {
    
  }
  start_time_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), start_time,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:OfflineMsg.start_time)
}
inline std::string* OfflineMsg::unsafe_arena_release_start_time() {
  // @@protoc_insertion_point(field_unsafe_arena_release:OfflineMsg.start_time)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return start_time_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void OfflineMsg::unsafe_arena_set_allocated_start_time(
    std::string* start_time) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (start_time != nullptr) {
    
  } else {
    
  }
  start_time_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      start_time, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:OfflineMsg.start_time)
}

// string end_time = 2;
inline void OfflineMsg::clear_end_time() {
  end_time_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& OfflineMsg::end_time() const {
  // @@protoc_insertion_point(field_get:OfflineMsg.end_time)
  return _internal_end_time();
}
inline void OfflineMsg::set_end_time(const std::string& value) {
  _internal_set_end_time(value);
  // @@protoc_insertion_point(field_set:OfflineMsg.end_time)
}
inline std::string* OfflineMsg::mutable_end_time() {
  // @@protoc_insertion_point(field_mutable:OfflineMsg.end_time)
  return _internal_mutable_end_time();
}
inline const std::string& OfflineMsg::_internal_end_time() const {
  return end_time_.Get();
}
inline void OfflineMsg::_internal_set_end_time(const std::string& value) {
  
  end_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void OfflineMsg::set_end_time(std::string&& value) {
  
  end_time_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:OfflineMsg.end_time)
}
inline void OfflineMsg::set_end_time(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  end_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:OfflineMsg.end_time)
}
inline void OfflineMsg::set_end_time(const char* value,
    size_t size) {
  
  end_time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:OfflineMsg.end_time)
}
inline std::string* OfflineMsg::_internal_mutable_end_time() {
  
  return end_time_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* OfflineMsg::release_end_time() {
  // @@protoc_insertion_point(field_release:OfflineMsg.end_time)
  return end_time_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void OfflineMsg::set_allocated_end_time(std::string* end_time) {
  if (end_time != nullptr) {
    
  } else {
    
  }
  end_time_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), end_time,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:OfflineMsg.end_time)
}
inline std::string* OfflineMsg::unsafe_arena_release_end_time() {
  // @@protoc_insertion_point(field_unsafe_arena_release:OfflineMsg.end_time)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return end_time_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void OfflineMsg::unsafe_arena_set_allocated_end_time(
    std::string* end_time) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (end_time != nullptr) {
    
  } else {
    
  }
  end_time_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      end_time, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:OfflineMsg.end_time)
}

// uint32 vol_10mA = 3;
inline void OfflineMsg::clear_vol_10ma() {
  vol_10ma_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OfflineMsg::_internal_vol_10ma() const {
  return vol_10ma_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OfflineMsg::vol_10ma() const {
  // @@protoc_insertion_point(field_get:OfflineMsg.vol_10mA)
  return _internal_vol_10ma();
}
inline void OfflineMsg::_internal_set_vol_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  vol_10ma_ = value;
}
inline void OfflineMsg::set_vol_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_vol_10ma(value);
  // @@protoc_insertion_point(field_set:OfflineMsg.vol_10mA)
}

// uint32 power = 4;
inline void OfflineMsg::clear_power() {
  power_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OfflineMsg::_internal_power() const {
  return power_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OfflineMsg::power() const {
  // @@protoc_insertion_point(field_get:OfflineMsg.power)
  return _internal_power();
}
inline void OfflineMsg::_internal_set_power(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  power_ = value;
}
inline void OfflineMsg::set_power(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_power(value);
  // @@protoc_insertion_point(field_set:OfflineMsg.power)
}

// -------------------------------------------------------------------

// HmiConfigMsg

// .HeaderMsg header = 1;
inline bool HmiConfigMsg::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool HmiConfigMsg::has_header() const {
  return _internal_has_header();
}
inline void HmiConfigMsg::clear_header() {
  if (GetArena() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::HeaderMsg& HmiConfigMsg::_internal_header() const {
  const ::HeaderMsg* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::HeaderMsg*>(
      &::_HeaderMsg_default_instance_);
}
inline const ::HeaderMsg& HmiConfigMsg::header() const {
  // @@protoc_insertion_point(field_get:HmiConfigMsg.header)
  return _internal_header();
}
inline void HmiConfigMsg::unsafe_arena_set_allocated_header(
    ::HeaderMsg* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HmiConfigMsg.header)
}
inline ::HeaderMsg* HmiConfigMsg::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::HeaderMsg* HmiConfigMsg::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:HmiConfigMsg.header)
  
  ::HeaderMsg* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::HeaderMsg* HmiConfigMsg::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::HeaderMsg>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::HeaderMsg* HmiConfigMsg::mutable_header() {
  // @@protoc_insertion_point(field_mutable:HmiConfigMsg.header)
  return _internal_mutable_header();
}
inline void HmiConfigMsg::set_allocated_header(::HeaderMsg* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:HmiConfigMsg.header)
}

// bool en_set_smb_chaCur_10mA = 2;
inline void HmiConfigMsg::clear_en_set_smb_chacur_10ma() {
  en_set_smb_chacur_10ma_ = false;
}
inline bool HmiConfigMsg::_internal_en_set_smb_chacur_10ma() const {
  return en_set_smb_chacur_10ma_;
}
inline bool HmiConfigMsg::en_set_smb_chacur_10ma() const {
  // @@protoc_insertion_point(field_get:HmiConfigMsg.en_set_smb_chaCur_10mA)
  return _internal_en_set_smb_chacur_10ma();
}
inline void HmiConfigMsg::_internal_set_en_set_smb_chacur_10ma(bool value) {
  
  en_set_smb_chacur_10ma_ = value;
}
inline void HmiConfigMsg::set_en_set_smb_chacur_10ma(bool value) {
  _internal_set_en_set_smb_chacur_10ma(value);
  // @@protoc_insertion_point(field_set:HmiConfigMsg.en_set_smb_chaCur_10mA)
}

// uint32 set_smb_disCur_10mA = 3;
inline void HmiConfigMsg::clear_set_smb_discur_10ma() {
  set_smb_discur_10ma_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiConfigMsg::_internal_set_smb_discur_10ma() const {
  return set_smb_discur_10ma_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiConfigMsg::set_smb_discur_10ma() const {
  // @@protoc_insertion_point(field_get:HmiConfigMsg.set_smb_disCur_10mA)
  return _internal_set_smb_discur_10ma();
}
inline void HmiConfigMsg::_internal_set_set_smb_discur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  set_smb_discur_10ma_ = value;
}
inline void HmiConfigMsg::set_set_smb_discur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_set_smb_discur_10ma(value);
  // @@protoc_insertion_point(field_set:HmiConfigMsg.set_smb_disCur_10mA)
}

// uint32 set_smb_chaCur_10mA = 4;
inline void HmiConfigMsg::clear_set_smb_chacur_10ma() {
  set_smb_chacur_10ma_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiConfigMsg::_internal_set_smb_chacur_10ma() const {
  return set_smb_chacur_10ma_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HmiConfigMsg::set_smb_chacur_10ma() const {
  // @@protoc_insertion_point(field_get:HmiConfigMsg.set_smb_chaCur_10mA)
  return _internal_set_smb_chacur_10ma();
}
inline void HmiConfigMsg::_internal_set_set_smb_chacur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  set_smb_chacur_10ma_ = value;
}
inline void HmiConfigMsg::set_set_smb_chacur_10ma(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_set_smb_chacur_10ma(value);
  // @@protoc_insertion_point(field_set:HmiConfigMsg.set_smb_chaCur_10mA)
}

// .OnlineMsg online1 = 5;
inline bool HmiConfigMsg::_internal_has_online1() const {
  return this != internal_default_instance() && online1_ != nullptr;
}
inline bool HmiConfigMsg::has_online1() const {
  return _internal_has_online1();
}
inline void HmiConfigMsg::clear_online1() {
  if (GetArena() == nullptr && online1_ != nullptr) {
    delete online1_;
  }
  online1_ = nullptr;
}
inline const ::OnlineMsg& HmiConfigMsg::_internal_online1() const {
  const ::OnlineMsg* p = online1_;
  return p != nullptr ? *p : *reinterpret_cast<const ::OnlineMsg*>(
      &::_OnlineMsg_default_instance_);
}
inline const ::OnlineMsg& HmiConfigMsg::online1() const {
  // @@protoc_insertion_point(field_get:HmiConfigMsg.online1)
  return _internal_online1();
}
inline void HmiConfigMsg::unsafe_arena_set_allocated_online1(
    ::OnlineMsg* online1) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(online1_);
  }
  online1_ = online1;
  if (online1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HmiConfigMsg.online1)
}
inline ::OnlineMsg* HmiConfigMsg::release_online1() {
  auto temp = unsafe_arena_release_online1();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::OnlineMsg* HmiConfigMsg::unsafe_arena_release_online1() {
  // @@protoc_insertion_point(field_release:HmiConfigMsg.online1)
  
  ::OnlineMsg* temp = online1_;
  online1_ = nullptr;
  return temp;
}
inline ::OnlineMsg* HmiConfigMsg::_internal_mutable_online1() {
  
  if (online1_ == nullptr) {
    auto* p = CreateMaybeMessage<::OnlineMsg>(GetArena());
    online1_ = p;
  }
  return online1_;
}
inline ::OnlineMsg* HmiConfigMsg::mutable_online1() {
  // @@protoc_insertion_point(field_mutable:HmiConfigMsg.online1)
  return _internal_mutable_online1();
}
inline void HmiConfigMsg::set_allocated_online1(::OnlineMsg* online1) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete online1_;
  }
  if (online1) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(online1);
    if (message_arena != submessage_arena) {
      online1 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, online1, submessage_arena);
    }
    
  } else {
    
  }
  online1_ = online1;
  // @@protoc_insertion_point(field_set_allocated:HmiConfigMsg.online1)
}

// .OfflineMsg offline1 = 6;
inline bool HmiConfigMsg::_internal_has_offline1() const {
  return this != internal_default_instance() && offline1_ != nullptr;
}
inline bool HmiConfigMsg::has_offline1() const {
  return _internal_has_offline1();
}
inline void HmiConfigMsg::clear_offline1() {
  if (GetArena() == nullptr && offline1_ != nullptr) {
    delete offline1_;
  }
  offline1_ = nullptr;
}
inline const ::OfflineMsg& HmiConfigMsg::_internal_offline1() const {
  const ::OfflineMsg* p = offline1_;
  return p != nullptr ? *p : *reinterpret_cast<const ::OfflineMsg*>(
      &::_OfflineMsg_default_instance_);
}
inline const ::OfflineMsg& HmiConfigMsg::offline1() const {
  // @@protoc_insertion_point(field_get:HmiConfigMsg.offline1)
  return _internal_offline1();
}
inline void HmiConfigMsg::unsafe_arena_set_allocated_offline1(
    ::OfflineMsg* offline1) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(offline1_);
  }
  offline1_ = offline1;
  if (offline1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HmiConfigMsg.offline1)
}
inline ::OfflineMsg* HmiConfigMsg::release_offline1() {
  auto temp = unsafe_arena_release_offline1();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::OfflineMsg* HmiConfigMsg::unsafe_arena_release_offline1() {
  // @@protoc_insertion_point(field_release:HmiConfigMsg.offline1)
  
  ::OfflineMsg* temp = offline1_;
  offline1_ = nullptr;
  return temp;
}
inline ::OfflineMsg* HmiConfigMsg::_internal_mutable_offline1() {
  
  if (offline1_ == nullptr) {
    auto* p = CreateMaybeMessage<::OfflineMsg>(GetArena());
    offline1_ = p;
  }
  return offline1_;
}
inline ::OfflineMsg* HmiConfigMsg::mutable_offline1() {
  // @@protoc_insertion_point(field_mutable:HmiConfigMsg.offline1)
  return _internal_mutable_offline1();
}
inline void HmiConfigMsg::set_allocated_offline1(::OfflineMsg* offline1) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete offline1_;
  }
  if (offline1) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(offline1);
    if (message_arena != submessage_arena) {
      offline1 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, offline1, submessage_arena);
    }
    
  } else {
    
  }
  offline1_ = offline1;
  // @@protoc_insertion_point(field_set_allocated:HmiConfigMsg.offline1)
}

// .OnlineMsg online2 = 7;
inline bool HmiConfigMsg::_internal_has_online2() const {
  return this != internal_default_instance() && online2_ != nullptr;
}
inline bool HmiConfigMsg::has_online2() const {
  return _internal_has_online2();
}
inline void HmiConfigMsg::clear_online2() {
  if (GetArena() == nullptr && online2_ != nullptr) {
    delete online2_;
  }
  online2_ = nullptr;
}
inline const ::OnlineMsg& HmiConfigMsg::_internal_online2() const {
  const ::OnlineMsg* p = online2_;
  return p != nullptr ? *p : *reinterpret_cast<const ::OnlineMsg*>(
      &::_OnlineMsg_default_instance_);
}
inline const ::OnlineMsg& HmiConfigMsg::online2() const {
  // @@protoc_insertion_point(field_get:HmiConfigMsg.online2)
  return _internal_online2();
}
inline void HmiConfigMsg::unsafe_arena_set_allocated_online2(
    ::OnlineMsg* online2) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(online2_);
  }
  online2_ = online2;
  if (online2) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HmiConfigMsg.online2)
}
inline ::OnlineMsg* HmiConfigMsg::release_online2() {
  auto temp = unsafe_arena_release_online2();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::OnlineMsg* HmiConfigMsg::unsafe_arena_release_online2() {
  // @@protoc_insertion_point(field_release:HmiConfigMsg.online2)
  
  ::OnlineMsg* temp = online2_;
  online2_ = nullptr;
  return temp;
}
inline ::OnlineMsg* HmiConfigMsg::_internal_mutable_online2() {
  
  if (online2_ == nullptr) {
    auto* p = CreateMaybeMessage<::OnlineMsg>(GetArena());
    online2_ = p;
  }
  return online2_;
}
inline ::OnlineMsg* HmiConfigMsg::mutable_online2() {
  // @@protoc_insertion_point(field_mutable:HmiConfigMsg.online2)
  return _internal_mutable_online2();
}
inline void HmiConfigMsg::set_allocated_online2(::OnlineMsg* online2) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete online2_;
  }
  if (online2) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(online2);
    if (message_arena != submessage_arena) {
      online2 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, online2, submessage_arena);
    }
    
  } else {
    
  }
  online2_ = online2;
  // @@protoc_insertion_point(field_set_allocated:HmiConfigMsg.online2)
}

// .OfflineMsg offline2 = 8;
inline bool HmiConfigMsg::_internal_has_offline2() const {
  return this != internal_default_instance() && offline2_ != nullptr;
}
inline bool HmiConfigMsg::has_offline2() const {
  return _internal_has_offline2();
}
inline void HmiConfigMsg::clear_offline2() {
  if (GetArena() == nullptr && offline2_ != nullptr) {
    delete offline2_;
  }
  offline2_ = nullptr;
}
inline const ::OfflineMsg& HmiConfigMsg::_internal_offline2() const {
  const ::OfflineMsg* p = offline2_;
  return p != nullptr ? *p : *reinterpret_cast<const ::OfflineMsg*>(
      &::_OfflineMsg_default_instance_);
}
inline const ::OfflineMsg& HmiConfigMsg::offline2() const {
  // @@protoc_insertion_point(field_get:HmiConfigMsg.offline2)
  return _internal_offline2();
}
inline void HmiConfigMsg::unsafe_arena_set_allocated_offline2(
    ::OfflineMsg* offline2) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(offline2_);
  }
  offline2_ = offline2;
  if (offline2) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HmiConfigMsg.offline2)
}
inline ::OfflineMsg* HmiConfigMsg::release_offline2() {
  auto temp = unsafe_arena_release_offline2();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::OfflineMsg* HmiConfigMsg::unsafe_arena_release_offline2() {
  // @@protoc_insertion_point(field_release:HmiConfigMsg.offline2)
  
  ::OfflineMsg* temp = offline2_;
  offline2_ = nullptr;
  return temp;
}
inline ::OfflineMsg* HmiConfigMsg::_internal_mutable_offline2() {
  
  if (offline2_ == nullptr) {
    auto* p = CreateMaybeMessage<::OfflineMsg>(GetArena());
    offline2_ = p;
  }
  return offline2_;
}
inline ::OfflineMsg* HmiConfigMsg::mutable_offline2() {
  // @@protoc_insertion_point(field_mutable:HmiConfigMsg.offline2)
  return _internal_mutable_offline2();
}
inline void HmiConfigMsg::set_allocated_offline2(::OfflineMsg* offline2) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete offline2_;
  }
  if (offline2) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(offline2);
    if (message_arena != submessage_arena) {
      offline2 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, offline2, submessage_arena);
    }
    
  } else {
    
  }
  offline2_ = offline2;
  // @@protoc_insertion_point(field_set_allocated:HmiConfigMsg.offline2)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_hmiMsg_2eproto
